server:  port: 9003
spring:  application:    name: cloudalibaba-nacos-provider-service
  cloud:    nacos:      discovery:        server-addr: 127.0.0.1:8848
        
management:  endpoints:    web:      exposure:        include:        - "*"
  