#server.port=8081
#spring.application.name=nacos-producer
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#management.endpoints.web.exposure.include=*

server:  port: 8401
spring:  application:    name: cloudalibaba-sentinel-service
  cloud:    nacos:      discovery:        server-addr: 127.0.0.1:8848
    sentinel:      transport:        dashboard: 127.0.0.1:8080
        #这里的 spring.cloud.sentinel.transport.port 端口配置
        #会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。
        #比如 Sentinel 控制台添加了一个限流规则，
        #会把规则数据 push 给这个 Http Server 接收，
        #Http Server 再将规则注册到 Sentinel 中。
        port: 8719
      datasource:        ds1: 
          nacos:
             server-addr: localhost:8848
             data-id: ${spring.application.name}
             group-id: DEFAULT_GROUP
             data-type: json
             rule-type: flow            
        
management:  endpoints:    web:      exposure:        include:        - "*"
  