server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:      seata:
        #自定义事物组的名称需要与seata-server中的对应        tx-service-group: mytest_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.117:3306/seata_order
    username: root
    password: root
       
feign:  hystrix:    enabled: false
 
logging:  level:    io:
      seata: info
      
mybatis:  mapper-locations: classpath:mapper/*.xml 

  