#server.port=8081
#spring.application.name=nacos-producer
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#management.endpoints.web.exposure.include=*

server:  port: 83
spring:  application:    name: cloudalibaba-nacos-order
  cloud:    nacos:      discovery:        server-addr: 127.0.0.1:8848
        
service-url:
    nacos-user-service: http://cloudalibaba-nacos-provider-service