server:
  port: 80

spring:  application:    name: cloud-order-service
# 请求连接的超时时间
#  ribbon.ConnectTimeout=2000
  # 请求处理的超时时间
#  ribbon.ReadTimeout=5000

#ribbon: 
#   ConnectTimeout: 5000
#   ReadTimeout: 5000

eureka:
  client:
    #表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: false
    #是否从eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,,http://eureka7003.com:7003/eureka

feign: 
   hystrix: 
      enabled: true